### ISSUE TITLE
When looking at FACTS output the most obvious first Focus variable selection is bad.

### ISSUE THREAD

**Issue by berryni** [el-meyer/airship#128]
I commonly want to Focus on Scenario.ID, and I commonly want to focus on, say Recruitment.Profile and Dose.Response.Profile, but I never want Scenario.ID, Recruitment.Profile, and Dose.Response.Profile.

If there is ever a column that is a "linear combination" of other columns and all are selected as focus variables, then the plots that we can make only use 1 level. It would be nice to warn people of this or prevent it from happening.

**Comment by el-meyer** [comment]
Will 
a) implement a new logic for FACTS data where the button options are "Choose Scenario" and "Choose Design Variants"
b) display a warning if linear combination is chosen

**Comment by el-meyer** [comment]
The two previous commits should fix this issue. Please have a look @berryni .

**Comment by el-meyer** [comment]
This is not entirely fixed. Currently one variables is removed and checked for uniqueness in the filter. This does not work when removing e.g. Scenario ID leads to non-uniqueness but removing Response Profile leads to uniqueness. 

![image](https://github.com/el-meyer/airship/assets/73820185/4065af8a-5e8d-4181-843c-6854fdaca684)
does not throw a warning
