### ISSUE TITLE
Labels in legend are missing

### ISSUE THREAD

**Issue by el-meyer** [el-meyer/airship#4]
When choosing a shape parameter, the label of this variable is not correctly displayed in the figure legend (also the label for the output variables is missing)

![grafik](https://user-images.githubusercontent.com/73820185/151361498-c779af50-eeb2-4f55-997f-5e833b23c910.png)

**Comment by majkamichal** [comment]
This should be helpful:

https://ggplot2-book.org/scales-guides.html

`base <- ggplot(toy, aes(const, up)) + 
  geom_point(aes(shape = txt, colour = txt)) + 
  scale_x_continuous(NULL, breaks = NULL)

base
base + labs(shape = "Split legend")
base + labs(shape = "Merged legend", colour = "Merged legend")`

**Comment by el-meyer** [comment]
With this commit, added common legend for shype and linetype. [bca44a2](https://github.com/el-meyer/sim_vis_shiny/commit/bca44a21d7d29421013610d409b3fab9706702bf)

**Comment by el-meyer** [comment]
Problem only appears in ggplot, not plotly.

**Comment by el-meyer** [comment]
Adding 
+ theme(legend.position="bottom")
has no effect either. Maybe this is overwritten somewhere later?
