### ISSUE TITLE
Allow the user to reorder columns

### ISSUE THREAD

**Issue by majkamichal** [el-meyer/airship#90]
https://rstudio.github.io/DT/extensions.html#:~:text=Customize%20TableTools%20Buttons-,3%20ColReorder,-You%20can%20click

**Comment by el-meyer** [comment]
It is now implemented for "Original Data", would be nice to also implement for "Summarized Data", "Focus Variables" and in the Plotted Data of every plot (i.e. in fnStandardOutput.R). 

I can also do it, let's see who has time first :)
