### ISSUE TITLE
`airship()` should have a parameter `data=NULL`

### ISSUE THREAD

**Issue by majkamichal** [el-meyer/airship#91]
**Idea**: the R/RStudio user should have a possibility of passing the data.frame with results directly to the shiny server:

1. The starter function `airship()` should contain an optional parameter `data=NULL`. 

2. In case `data != NULL` It should be checked if the `data` is a data.frame/tibble/data.table.

3. If the user runs the app with the custom data (`data!=NULL and is data.frame`), the data should be passed directly to the shiny server via `options()`. See: https://github.com/majkamichal/easyPlot/blob/dba68e608d2b396f2043a398d2a3e25de12398b7/R/easyPlot.R#L47 and https://github.com/majkamichal/easyPlot/blob/dba68e608d2b396f2043a398d2a3e25de12398b7/inst/app/server.R#L17 
4. If the user runs the app with `data=NULL` then the app starts normally and the user must upload a file

**Comment by el-meyer** [comment]
Great suggestion! This will be fixed with a future version, as soon as the interface with FACTS is established.

**Comment by el-meyer** [comment]
Allow passing of csv data via a local path (will be used by FACTS).
